config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :posts do
    member do
      put "like", to: "posts#upvote"
      put "dislike", to: "posts#downvote"
    end
    resources :comments 
  end
  root 'posts#index'
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :post
end

app/models/post.rb
class Post < ActiveRecord::Base
    belongs_to :user
    acts_as_votable
    has_attached_file :image, :styles => { :medium => "700x500#", :small => "350x250>" }
    validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
    has_many :comments
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :posts
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :username
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    before_action :find_post, only: [:create, :destroy, :edit, :update]
    
    def new
    end
    
    def create
        @comment = @post.comments.create(comment_params)
        @comment.user = current_user if current_user
        
        if @comment.save
            redirect_to @post
        else
            render :new
        end
    end
    
    def edit
        @comment = @post.comments.find(params[:id])
    end
    
    def update
        @comment = @post.comments.find(params[:id])
        if @comment.update(comment_params)
            redirect_to @post
        else
            render :edit
        end
    end
    
    def destroy
        @comment = @post.comments.find(params[:id])
        @comment.destroy
        redirect_to @post
    end
    
    private
    def comment_params
        params.require(:comment).permit(:content)
    end
    
    def find_post
        @post = Post.find(params[:post_id])
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    before_action :find_post, only: [:show, :edit, :update, :destroy, :upvote, :downvote]
    before_action :authenticate_user!, except: [:index, :show]
    
    def index
        @posts = Post.all.order('created_at DESC')
    end
    
    def show
        @random_post = Post.where.not(id: @post).order("RANDOM()").first
    end
    
    def new
        @post = current_user.posts.build
    end
    
    def create
        @post = current_user.posts.build(post_params)
        if @post.save
            redirect_to @post
        else
            render :new
        end
    end
    
    
    def edit 
    end
    
    def update
        if @post.update(post_params)
            redirect_to @post
        else
            render :edit
        end
    end
    
    def destroy
        @post.destroy
        redirect_to root_path
    end
    
    def upvote
        @post.upvote_by current_user
        redirect_to :back
    end
    
    def downvote
        @post.downvote_by current_user
        redirect_to :back
    end
    
    private
    
    def post_params
        params.require(:post).permit(:title, :link, :description, :image)
    end
    
    def find_post
        @post = Post.find(params[:id])
    end
        
        
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_comment.html.haml
.comment
    %p= comment.user.email
    %p= comment.content

app/views/comments/_form.html.haml
= simple_form_for([@post, @post.comments.build]) do |f|
    = f.input :content
    = f.button :submit

app/views/layouts/application.html.haml
!!!
%html
%head
	%title Muse
	= stylesheet_link_tag    'application', media: 'all'
	= javascript_include_tag 'application'
	%link{:rel => "stylesheet", :href => "http://cdnjs.cloudflare.com/ajax/libs/normalize/3.0.3/normalize.min.css"}
	%link{:rel => "stylesheet", :href => "//maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css"}/
	= csrf_meta_tags
%body
	%header
		.wrapper.clearfix
			#logo= link_to "Muse", root_path
			%nav
				- if user_signed_in?
					= link_to current_user.username, edit_user_registration_path
					= link_to "Add New Inspiration", new_post_path, class: "button"
				- else
					= link_to "Sign in", new_user_session_path
					= link_to "Sign Up", new_user_registration_path, class: "button"
	%p.notice= notice
	%p.alert= alert
	.wrapper
		= yield

app/views/posts/_form.html.haml
= simple_form_for @post do |f|
    = f.input :image
    = f.input :title
    = f.input :link
    = f.input :description
    = f.button :submit
    
    

app/views/posts/edit.html.haml
%h1 Edit your inspiration
= render "form"
= link_to "cancel", @post

app/views/posts/index.html.haml
- if user_signed_in?
	%p#intro
		Hello
		= current_user.username
		%br/
		%span
			Share your inspiration and see what's inspiring others.
- else
	%p#intro
		What's your muse?
		%br/
		%span
			Share your inspiration and see what's inspiring others.
#posts
	- @posts.each do |post|
		.post
			.post_image
				= link_to (image_tag post.image.url(:small)), post
			.post_content
				.title
					%h2= link_to post.title, post
				.data.clearfix
					%p.username
						Shared by
						= post.user.username
					%p.buttons
						%span
							%i.fa.fa-comments-o
							= post.comments.count
						%span
							%i.fa.fa-thumbs-o-up
							= post.get_likes.size

app/views/posts/new.html.haml
%h1 Write new inspiration here
= render "form"
= link_to "cancel", root_path

app/views/posts/show.html.haml
#post_show
	%h1= @post.title
	%p.username
		Shared by
		= @post.user.username
		about
		= time_ago_in_words(@post.created_at)
	.clearfix
		.post_image_description
			= image_tag @post.image.url(:medium)
			.description= simple_format(@post.description)
		.post_data
			= link_to "Visit Link", @post.link, class: "button"
			= link_to like_post_path(@post), method: :put, class: "data" do
				%i.fa.fa-thumbs-o-up
				= pluralize(@post.get_upvotes.size, "Like")
			= link_to dislike_post_path(@post), method: :put, class: "data" do
				%i.fa.fa-thumbs-o-down
				= pluralize(@post.get_downvotes.size, "Dislike")
			%p.data
				%i.fa.fa-comments-o
				= pluralize(@post.comments.count, "Comment")
			- if @post.user == current_user
				= link_to "Edit", edit_post_path(@post), class: "data"
				= link_to "Delete", post_path(@post), method: :delete, data: { confirm: "Are you sure?" }, class: "data"
		
		#random_post
			%h3 Random Inspiration
			.post
				.post_image
					= link_to (image_tag @random_post.image.url(:medium)), post_path(@random_post)
				.post_content
					.title
						%h2= link_to @random_post.title, post_path(@random_post)
					.data.clearfix
						%p.username
							Shared by
							= @random_post.user.username
						%p.buttons
							%span
								%i.fa.fa-comments-o
								= @random_post.comments.count
							%span
								%i.fa.fa-thumbs-o-up
								= @random_post.get_likes.size

#comments
	%h2.comment_count= pluralize(@post.comments.count, "Comment")
	= render @post.comments
	= render "comments/form"